name: Linter

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  run-eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: Install modules
        run: npm i
      - name: Run linters
        run: npm run lint
      - name: Run typecheck
        run: npm run types:check